apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-java
  labels:
    app: microservice-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-java
  template:
    metadata:
      labels:
        app: microservice-java
    spec:
      containers:
      - name: microservice-java
        image: smelo23/microservice-java:1.0.0
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: microservice-java-config
        startupProbe:
          initialDelaySeconds: 20
          httpGet:
            path: /actuator/health
            port: 8080
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
